CREATE USER 'bot'@'localhost' IDENTIFIED BY 'bot' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;
GRANT ALL PRIVILEGES ON * . * TO 'bot'@'localhost' WITH GRANT OPTION;
CREATE DATABASE `bot`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON `bot` . * TO 'bot'@'localhost' WITH GRANT OPTION;