using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WotlkClient.Constants
{
    public enum ChatMsg
    {
        System = 0,    //28,   CHAT_MSG_SYSTEM                 = 0x00,         0
        Say = 1,
        Party = 2,
        Raid = 3,
        Guild = 4,
        Yell = 6,
        Whisper = 7,
        Channel = 17,
        System2 = 28,

    };

    public enum Languages
    {
        Universal = 0x00,
        Orcish = 0x01,
        Darnassian = 0x02,
        Taurahe = 0x03,
        Dwarvish = 0x06,
        Common = 0x07,
        Thelessian = 0x0A,
        Gnomish = 0x0D,
        Trollish = 0x0E,
        Gutterspeak = 0x21,
        Draenei = 0x23,
        NUM_LANGUAGES = 0x24
    };

    public enum EmoteType : int
    {
        AGREE = 1,
        AMAZE,
        ANGRY,
        APOLOGIZE,
        APPLAUD,
        BASHFUL,
        BECKON,
        BEG,
        BITE,
        BLEED,
        BLINK,
        BLUSH,
        BONK,
        BORED,
        BOUNCE,
        BRB,
        BOW,
        BURP,
        BYE,
        CACKLE,
        CHEER,
        CHICKEN,
        CHUCKLE,
        CLAP,
        CONFUSED,
        CONGRATULATE,
        COUGH,
        COWER,
        CRACK,
        CRINGE,
        CRY,
        CURIOUS,
        CURTSEY,
        DANCE,
        DRINK,
        DROOL,
        EAT,
        EYE,
        FART,
        FIDGET,
        FLEX,
        FROWN,
        GASP,
        GAZE,
        GIGGLE,
        GLARE,
        GLOAT,
        GREET,
        GRIN,
        GROAN,
        GROVEL,
        GUFFAW,
        HAIL,
        HAPPY,
        HELLO,
        HUG,
        HUNGRY,
        KISS,
        KNEEL,
        LAUGH,
        LAYDOWN,
        MASSAGE,
        MOAN,
        MOON,
        MOURN,
        NO,
        NOD,
        NOSEPICK,
        PANIC,
        PEER,
        PLEAD,
        POINT,
        POKE,
        PRAY,
        ROAR,
        ROFL,
        RUDE,
        SALUTE,
        SCRATCH,
        SEXY,
        SHAKE,
        SHOUT,
        SHRUG,
        SHY,
        SIGH,
        SIT,
        SLEEP,
        SNARL,
        SPIT,
        STARE,
        SURPRISED,
        SURRENDER,
        TALK,
        TALKEX,
        TALKQ,
        TAP,
        THANK,
        THREATEN,
        TIRED,
        VICTORY,
        WAVE,
        WELCOME,
        WHINE,
        WHISTLE,
        WORK,
        YAWN,
        BOGGLE,
        CALM,
        COLD,
        COMFORT,
        CUDDLE,
        DUCK,
        INSULT,
        INTRODUCE,
        JK,
        LICK,
        LISTEN,
        LOST,
        MOCK,
        PONDER,
        POUNCE,
        PRAISE,
        PURR,
        PUZZLE,
        RAISE,
        READY,
        SHIMMY,
        SHIVER,
        SHOO,
        SLAP,
        SMIRK,
        SNIFF,
        SNUB,
        SOOTHE,
        STINK,
        TAUNT,
        TEASE,
        THIRSTY,
        VETO,
        SNICKER,
        STAND,
        TICKLE,
        VIOLIN,
        SMILE,
        RASP,
        PITY,
        GROWL,
        BARK,
        SCARED,
        FLOP,
        LOVE,
        MOO,
        COMMEND,
        TRAIN,
        HELPME,
        INCOMING,
        CHARGE,
        FLEE,
        ATTACKMYTARGET,
        OOM,
        FOLLOW,
        WAIT,
        HEALME,
        OPENFIRE,
        FLIRT,
        JOKE,
        GOLFCLAP,
        WINK,
        PAT,
        SERIOUS,
        MOUNTSPECIAL,
        GOODLUCK,
        BLAME,
        BLANK,
        BRANDISH,
        BREATH,
        DISAGREE,
        DOUBT,
        EMBARRASS,
        ENCOURAGE,
        ENEMY,
        EYEBROW,
        TOAST,
    }
}
